# Dockerfile.cleanup-job
FROM python:3.12-slim-bookworm

ENV PYTHONUNBUFFERED=1
ENV APP_HOME=/home/appuser
ENV PYTHONPATH=${APP_HOME}
ENV PATH="${PATH}:${APP_HOME}/.local/bin"
# Set FLASK_ENV to development for local Minikube testing
ENV FLASK_ENV=development

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    git \
    curl \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
    
RUN adduser --disabled-password --gecos "" appuser
WORKDIR ${APP_HOME}
RUN chown appuser:appuser ${APP_HOME}
USER appuser

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . ${APP_HOME}

# Command to run the cleanup job
CMD ["python", "server/cleanup_expired_posts.py"]